<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Acme.InternalApi/Acme.InternalApi.csproj" />
    <ProjectReference Include="../../src/CompanyGuard.Analyzers/CompanyGuard.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <AdditionalFiles Include="companyguard.json" />
  </ItemGroup>
</Project>
